import type { Metadata } from "next";
import { Inter, Epilogue } from "next/font/google";
import "./globals.css";
import Provider from "./_trpc/Provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/toaster";
import { ReCaptchaProvider } from "./_recaptcha/ReCaptchaProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const epilogue = Epilogue({ subsets: ["latin"], variable: "--font-epilogue" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={`${inter.variable} ${epilogue.variable} ${epilogue.variable} font-sans`}
        >
          <ReCaptchaProvider>
            <Provider>{children}</Provider>
            <Toaster />
          </ReCaptchaProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
